version: "3.8"

services:
    matchmaking_db:
        container_name: matchmaking_db
        image: postgres:alpine
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data/
        env_file:
            - .env
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db_data: